### ISSUE TITLE
Cannot assign .... ComplexQuery::$columns of type array

### ISSUE THREAD

**Issue by emresasi** [arm092/livewire-datatables#10]
Hello, my code is as follows. When I make $complex = true, Cannot assign Illuminate\Support\Collection to property Arm092\LivewireDatatables\Livewire\ComplexQuery::$columns of type array

I am getting the error. How can I solve this? In the original repo, $complex = true was working smoothly, but when I switched to your repo, I cannot set $complex = true. I also tried a fresh Laravel installation and encountered the same problem there.

class AverageDatatable extends LivewireDatatable
{
    use Enum, Summarize;

    public ?string $hideable = 'select';
    public bool $exportable = true;
    public $complex = true;
    public bool $persistComplexQuery = true;
    public ?string $afterTableSlot = 'components.selected';

    public function builder(): Builder
    {
        return Average::query()
            ->leftJoin('advertisers', 'advertisers.id', '=', 'averages.advertiser_id');

    }

    public function getColumns(): array|Model
    {
        return [
            Column::name('advertisers.name')
                ->label(__('Advertiser'))
                ->defaultSort('asc')
                ->searchable('name')
                ->hideable()
                ->filterable(),

            Column::name("quarter_id")
                ->label('Quarter')
                ->hideable()
                ->view('components.datatable.quarter_filter')
                ->filterable(Quarter::toArray()),

            Column::name("quarter_year")
                ->label('Quarter Year')
                ->hideable()
                ->filterable(years()),
        ];

    }
}

**Comment by arm092** [comment]
I've realesed [new version](https://github.com/arm092/livewire-datatables/releases/tag/2.0.4), please update and give feedback

**Comment by emresasi** [comment]
now Cannot assign null to property Arm092\LivewireDatatables\Livewire\ComplexQuery::$savedQueries of type array

now there is this problem

**Comment by arm092** [comment]
try [this](https://github.com/arm092/livewire-datatables/releases/tag/2.0.5) one, please (new release)

**Comment by emresasi** [comment]
Okay, there is no error at the moment, the page appears, but when I add rules or groups, filtering in the table does not work.

**Comment by arm092** [comment]
Please, can you try to fix the problems, and make PR? I will review, merge and release it. Just now I don't have time to fix and test all functionalities

**Comment by arm092** [comment]
Approved and merged your PR, thanks.
Here is [new version](https://github.com/arm092/livewire-datatables/releases/tag/2.0.6)
