### ISSUE TITLE
Hideable columns problem

### ISSUE THREAD

**Issue by emresasi** [arm092/livewire-datatables#11]
I get this problem when we do not add this to all columns with the undefined array key "hideable" problem. I wonder if this has been made mandatory in all columns in this repo?

![hideable](https://github.com/arm092/livewire-datatables/assets/6942826/c67ba37b-1a0b-409a-be1e-9eeed8575d9f)

**Comment by arm092** [comment]
https://github.com/arm092/livewire-datatables/releases/tag/2.0.6
