### ISSUE TITLE
Problems with export in Excel

### ISSUE THREAD

**Issue by esedArk** [arm092/livewire-datatables#13]
Hi, when I export the table I have this error.

<img width="1106" alt="image" src="https://github.com/arm092/livewire-datatables/assets/2690260/8d1470e1-5415-4755-a90a-43837de99b8c">

I've installed 

composer require maatwebsite/excel:^3.1 and I followed this url, https://docs.laravel-excel.com/3.1/getting-started/installation.html

**Comment by esedArk** [comment]
<img width="674" alt="image" src="https://github.com/arm092/livewire-datatables/assets/2690260/74bd37ac-097f-4304-aedb-61b436acabb8">

**Comment by arm092** [comment]
hey bro, sorry for delay
I will check it in few days..
If you know where is the problem and can solve it, you can create pull request, I will merge it

**Comment by arm092** [comment]
Fixed bro:
https://github.com/arm092/livewire-datatables/releases/tag/2.1.0
