### ISSUE TITLE
Undefined array key

### ISSUE THREAD

**Issue by tiagokb** [arm092/livewire-datatables#15]
![image](https://github.com/arm092/livewire-datatables/assets/39976202/04a3bd1f-9cb0-4c43-86fe-0e8773c43f73)

Does anyone know how to solve this or any tips for finding a solution?

**Comment by arm092** [comment]
Please provide more info.. There is no exception related anything in your screenshot (I mean in this frame there is no any array element getting)

**Comment by arm092** [comment]
Fixed bro:
https://github.com/arm092/livewire-datatables/releases/tag/2.1.0
