### ISSUE TITLE
repository pattern

### ISSUE THREAD

**Issue by alukardua1** [arm092/livewire-datatables#23]
I use the query output from the repository pattern, and it detects the error "Property type not supported in Livewire for property: [{}]"
in the constructor, the following code
exists a constructor of 
```
public functions (): Builder
    {
        $this - >repository = new UserRepository();
        returns $this - >repository - >queryUsers();
    }
```

**Comment by arm092** [comment]
I can't help you... your code snippet has syntax problems, and I don't know where you have written it

**Comment by alukardua1** [comment]
I've already figured it out, there was a problem in downloading the livewire itself
