### ISSUE TITLE
How to Filter Encrypted Advertiser Names in the Database?

### ISSUE THREAD

**Issue by emresasi** [arm092/livewire-datatables#24]
Hello, in my project, advertiser names are stored encrypted in the database. I can decrypt them when displaying in the table, but when I try to filter by brand name, it doesn't work because the filter is not encrypted. Is there a way to achieve this?

**Comment by arm092** [comment]
You can try to use an array with encrypted values and decrypted keys as filter. And please for such cases open a [discussion](https://github.com/arm092/livewire-datatables/discussions) instead of an issue.
