### ISSUE TITLE
$defaultSort must not be accessed before initialization

### ISSUE THREAD

**Issue by vgoncalves13** [arm092/livewire-datatables#4]
Hello, thanks for the fork.

Im trying configure it, but i got the following error.

https://flareapp.io/share/pPvK0L17

My Livewire Component:

```php
<?php

namespace App\Livewire\Datatables\PartnerItem;

use App\Models\PartnerItem;
use Arm092\LivewireDatatables\Column;
use Arm092\LivewireDatatables\Livewire\LivewireDatatable;

class PartnerItemTable extends LivewireDatatable
{
    public $model = PartnerItem::class;

    public function columns(): array
    {
        return [
            Column::name('name')
        ];
    }
}
```

My test view

```html
<livewire:datatable model="App\Models\PartnerItem" />
```
I made this change in the Column class and my table renders
```php
    public bool|string $defaultSort = false;
```

Appreciate any help.

**Comment by johnneijzen** [comment]
Also having same problem one did i do that fix error is to uncomment public array $freshColumns = []; in vendor/arm092/livewire-datatables/src/Livewire/LivewireDatatable.php but now display empty table even though it did fetch records 

![image](https://github.com/arm092/livewire-datatables/assets/1343960/04612d26-89a1-4313-9484-d9f1db06fdce)

**Comment by soycake** [comment]
I having same problem too.

**Comment by arm092** [comment]
Will fix it now, guys

**Comment by arm092** [comment]
> ```
>  public function columns(): array
> ```

But this should be `getColumns()` and properties types also should be defined

**Comment by arm092** [comment]
[**Changelog:**](https://github.com/arm092/livewire-datatables/releases/tag/2.0.1)
