### ISSUE TITLE
How call datatable in blade view? 

### ISSUE THREAD

**Issue by stojankukrika** [arm092/livewire-datatables#5]
Hi,
Thanks for the update on livewire 3. Finally, someone made it!

I have two questions:
1. How to call a table in blade view? In the forked package, it was <livewire:team-table/>.?
2. How to call a table with forward params? In forked version it was something like <livewire:team-table :params=$teamGroup->id/>

https://github.com/MedicOneSystems/demo-livewire-datatables/blob/master/resources/views/complex.blade.php#L7

Regards,
SK

**Comment by arm092** [comment]
It should be `<livewire:datatables.team-table :param="$something"/>` for newly created datatables in `App\Livewire\Datatables\` directory

**Comment by stojankukrika** [comment]
It may work, but it didn't work without a model defined. I get this error: "Typed property Arm092\LivewireDatatables\Livewire\LivewireDatatable::$model must not be accessed before initialization" even though I have columns and builder methods. And when I add the model, it reads only columns from this model, not from the builder :(

**Comment by arm092** [comment]
[Try to update](https://github.com/arm092/livewire-datatables/releases/tag/2.0.2)
