### ISSUE TITLE
How to run in livewire v3 

### ISSUE THREAD

**Issue by dikeshraj** [arm092/livewire-datatables#9]
When running in laravel 10 and Livewire 3 I got this issue how to fix it..

Declaration of App\Livewire\CheckTable::builder() must be compatible with Arm092\LivewireDatatables\Livewire\LivewireDatatable::builder(): Illuminate\Database\Eloquent\Builder

use Arm092\LivewireDatatables\Livewire\LivewireDatatable;
use Arm092\LivewireDatatables\NumberColumn;
use Livewire\Component;
use Modules\AssignItem\Models\AssignItem;

class CheckTable extends LivewireDatatable
{
    // public function render()
    // {
    //     return view('livewire.check-table');
    // }

    public function builder()
    {
        return AssignItem::query();
    }

    public function columns()
    {
        return [
            NumberColumn::name('id')
            ->label('ID')
            ->filterable(),

        ];
    }
} this is livewire class and in blade  @livewire('check-table')

**Comment by arm092** [comment]
Check readme. Your definitions of methods extended from LivewireDatatable should be the same as in the parent class (params types, return type)
